### ISSUE TITLE
FanLinc 2475F Support

### ISSUE THREAD

**Issue by heatvent** [pyinsteon/pyinsteon#152]
I have a few fanlincs in HA and they seem to be pulled in as on/off devices.  The fan side of the fanlinc has 4 states off, low, med, high.  I can't see how to access these to properly control the fanlinc.  Do I need to do something to manually configure?  (FYI, I am new to HA)

From what I can tell, the 2475F is pulled in as the following which I think is a dimmable light?

Device info
2475F (0x01, 0x2e)
by Smart Home
Connected via Insteon Hub
Firmware: 45 Engine Version: i2cs

My goal here is to have a keypadlinc control the fanlinc.  I have the light wired to the main on the keypadlinc rather than the fanlinc so when I activate the main switch on the keypadlinc in HA it works fine.  

For the fan, given there isn't a low, med or high not sure what to do.  Off seems to turn the fan off and on seems to either go to  low setting.  Sending multiple on's just kept it on low (didn't increment through speeds).

Looking at how the keypadlinc is defined, I am guessing that the light and each of the fan settings are different groups.  Below are the keypadlinc and fanlinc, respectively, from my insteon_devices.json file:

      "7687": {
        "memory": 7687,
        "in_use": true,
        "controller": true,
        "high_water_mark": false,
        "bit5": true,
        "bit4": false,
        "group": 0,
        "target": "3c41e2",
        "data1": 1,
        "data2": 66,
        "data3": 69
      },
      "7679": {
        "memory": 7679,
        "in_use": true,
        "controller": true,
        "high_water_mark": false,
        "bit5": true,
        "bit4": false,
        "group": 3,
        "target": "3c41e2",
        "data1": 0,
        "data2": 0,
        "data3": 0
      },
      "7671": {
        "memory": 7671,
        "in_use": true,
        "controller": false,
        "high_water_mark": false,
        "bit5": true,
        "bit4": false,
        "group": 1,
        "target": "3c41e2",
        "data1": 0,
        "data2": 0,
        "data3": 0
      },
      "7663": {
        "memory": 7663,
        "in_use": true,
        "controller": false,
        "high_water_mark": false,
        "bit5": true,
        "bit4": false,
        "group": 3,
        "target": "3c41e2",
        "data1": 0,
        "data2": 0,
        "data3": 0
      },
      "7655": {
        "memory": 7655,
        "in_use": true,
        "controller": true,
        "high_water_mark": false,
        "bit5": true,
        "bit4": false,
        "group": 5,
        "target": "3c41e2",
        "data1": 0,
        "data2": 0,
        "data3": 0
      },
      "7647": {
        "memory": 7647,
        "in_use": true,
        "controller": true,
        "high_water_mark": false,
        "bit5": true,
        "bit4": false,
        "group": 6,
        "target": "3c41e2",
        "data1": 0,
        "data2": 0,
        "data3": 0
      },
      "7639": {
        "memory": 7639,
        "in_use": true,
        "controller": false,
        "high_water_mark": false,
        "bit5": true,
        "bit4": false,
        "group": 5,
        "target": "3c41e2",
        "data1": 0,
        "data2": 0,
        "data3": 0
      },
      "7631": {
        "memory": 7631,
        "in_use": true,
        "controller": false,
        "high_water_mark": false,
        "bit5": true,
        "bit4": false,
        "group": 6,
        "target": "3c41e2",
        "data1": 0,
        "data2": 0,
        "data3": 0
      },
      "7623": {
        "memory": 7623,
        "in_use": true,
        "controller": true,
        "high_water_mark": false,
        "bit5": true,
        "bit4": false,
        "group": 254,
        "target": "3c41e2",
        "data1": 0,
        "data2": 0,
        "data3": 0
      },

      "7751": {
        "memory": 7751,
        "in_use": true,
        "controller": true,
        "high_water_mark": false,
        "bit5": true,
        "bit4": false,
        "group": 0,
        "target": "477ed7",
        "data1": 1,
        "data2": 46,
        "data3": 69

**Comment by teharris1** [comment]
What you are trying to do here is very common. What you need is to link the devices using the proper settings. Here are the steps:
1. Turn the fan to the speed you want the KPL button to set it to
2. Link the KPL and the fan with the KPL as a controller (see manual page 10)
3. Repeat for the different speeds you want to control.
Here is the link to the manual (http://cache.insteon.com/pdf/2486D.pdf)
