### ISSUE TITLE
Add ALDB read/write capabilities for version 1 devices

### ISSUE THREAD

**Issue by teharris1** [pyinsteon/pyinsteon#211]
Per the discussion here:
https://github.com/home-assistant/core/issues/71375

Version 1 devices require peak/poke commands for read/write functions to manage the All-Link Database. This request will add the read/write capabilities via peak/poke commands.

**Comment by teharris1** [comment]
I have started on this code. I believe I have the peek piece working. I am hoping to have the poke piece done today or Tuesday. How comfortable are you working at the operating system level with installing python libraries or running a command line editor?

**Comment by LSR19** [comment]
I’m not a programmer, but can learn what I need to and will work at figuring things out until I’m successful   I recently installed a a several python pqckages when I installed the hass_smarthings_removal program.  It took a while to get past several install errors but after googling and installing some python libraries, I got past all the errors.  So I understand at least this python:  py -m install “program_name”.

**Comment by teharris1** [comment]
The other good news is I have 8 version 1 devices that use both the "new" methods and the peek/poke methods. So I can test on my own devices. I suggest I get it to a point where it is generally available in Home Assistant before you try to fiddle around with it. The challenge with peek/poke approach is it is easy to mess up the device if I make a mistake with the code. I would prefer to break my own devices rather than someone else's. I think I will be able to get it into HA in about 2 - 3 weeks.

**Comment by LSR19** [comment]
Sounds encouraging.  Let me know if there is anything I can do.  

BTW - I notice that sometimes HA doesn’t update a device’s status so HA and the device get out of sync (eg, a device or entity is off but HA thinks it is on).  This seems to occur when something other than HA activates a device - for instance, if the device is turned on/off locally (eg, wall switch) or if a device was turned on/off by a mini-remote. 

Does your code ping devices regularly for status updates?  Is there any way to enable a manual status update if the devices and HA lose sync?

**Comment by jsetton** [comment]
@teharris1 Out of curiosity, any reason why you decided to use standard Peek/Poke One Byte requests opposed to using the extended version which read/write an entire record in one request?

I unfortunately don't have I1 devices to test with but it seems to be a lot of extra overhead getting a single database record in 8 requests. I was going over the [2005 Developers Guide](https://github.com/pyinsteon/dev_guides/raw/master/INSTEON_Developers_Guide_20051014a.pdf) and found Peek/Poke link database record extended request examples starting on page 73.

**Comment by danielduerr** [comment]
@jsetton I think the context of this ticket is around I1 (version 1) devices, hence peek/poke is the only way.  I am pretty sure pyinsteon already has/had I2 (version 2) support.

**Comment by jsetton** [comment]
> hence peek/poke is the only way

I understood that part. My point is that there are two types of peek/poke request based on its message type. The standard one only interacts with one byte at a time while the extended one can technically interacts with up to 15 bytes at a time.

The difference in speed to read/write an entire database would be significant.

**Comment by teharris1** [comment]
This has been released in version 1.3.0 and has been submitted to Home Assistant for approval.

**Comment by jsetton** [comment]
@teharris1 I am not sure if you saw my comments above. Any chance you could way in on using standard over extended Peek/Poke requests to interact with I1 device link database? Is it a matter of the extended version potentially not being available in all I1 devices?

**Comment by teharris1** [comment]
@jsetton yes, I did see your note and I really appreciate bringing that forward. I researched that a bit and it is an easy change to make in the system. My only concern is that I was able to look at how v1 devices are handled in HouseLinc, the old Insteon provided PC program. In that system, they don't use extended peek/poke messages. So I am fine to try it with an extended peek, but not an extended poke. So the system will work as follows:

1. Try the standard ALDB read
2. If that fails, try an extended peek
3. If that fails try a standard peek

Thoughts?

**Comment by jsetton** [comment]
@teharris1 It sounds good to me. I am actually interested about the test result against an I1 device which you seem to have at your disposal.

**Comment by teharris1** [comment]
I actually don't have any i1 devices. I only have i2 and i2CS devices. However, the i2 devices still support the peek/poke ability. The i2CS devices no longer support it. Hopefully, the i2 devices respond the same way as the i1 devices.

**Comment by teharris1** [comment]
Unfortunately, the i2 devices that I have tested do not respond with an extended message for the direct ACK. I am not surprised since the Direct ACK is never an extended message for any other message type. This means that the device only returns one byte at a time.

**Comment by jsetton** [comment]
Thanks for testing. I missed the part that the response was expected to be in direct ACK extended message. I somehow thought it was the standard direct ACK followed by an extended direct message.

As a matter a fact, looking at the more recent developer's guides, the extended peek/poke methods are no longer mentioned. So it looks like the standard one byte request is the only option for I1 devices.

**Comment by teharris1** [comment]
Released in 1.3.1.
