### ISSUE TITLE
Thermostats no longer working in 2023.4.x

### ISSUE THREAD

**Issue by veinoffeeling** [pyinsteon/pyinsteon#330]
Latest HA updates appear to have broken thermostats as outlined in this thread:
https://community.home-assistant.io/t/2023-4-broke-insteon-thermostat-integration/558223/2

**Comment by stevenakrause** [comment]
Any updates on this?

**Comment by teharris1** [comment]
This has been resolved in `pyinsteon` version 1.4.2 which was released a few days ago. It is slated for HA release 2023.4.6.

**Comment by stevenakrause** [comment]
> Collaborator

thanks!
