### ISSUE TITLE
Not checking responders when broadcast message is dropped

### ISSUE THREAD

**Issue by teharris1** [pyinsteon/pyinsteon#356]
In some scenarios, the broadcast message from a device is dropped and only the all-link cleanup message is heard. In this scenario, responders are not being identified correctly and therefore not being queried for their state.

**Comment by teharris1** [comment]
Fixed in 1.5.0

**Comment by EffBe** [comment]
Hi Tom - trying you here as I am following the GitHub devs; having issues
with a Venstar Thermostat Adapter; do you have any info on how to properly
configure this adapter in Home Assistant? It gets detected by your
integration, but then it reports weird data and interacting with it is
impossible. Here are a few screen captures:
[image: image.png]

[image: image.png]
[image: image.png]
Says Idle (Off) but its on, in cooling mode. And I can reassure you, its
not -17.8 C in my house at the moment...!!!

Any help you can provide would be great. Maybe I need to adjust
something in the pairing process?!

Regards,
Francis
