### ISSUE TITLE
using run_tool.py, list_devices and find_broken_links commands report format/display errors

### ISSUE THREAD

**Issue by jig432** [pyinsteon/pyinsteon#62]
I am running a PLM (usb) controlled by home assistant. 
(from the insteon_devices.jason info:
    "address": "20f4f9",
    "cat": 3,
    "subcat": 21,
    "firmware": 155,
    "engine_version": 3,
)

When invoking list_devices, I get an unknown format code error on the first entry.  Based on hacking/debugging, it looks like the first device is the PLM and it has "network_bridges" (?) as the category.

bash-5.0# python3 run_tool.py
STDOUT: Set log level to 20
The command line module for pyinsteon is designed to test devices and perform certain common functions.
pyinsteon: connect /dev/ttyUSB0
pyinsteon: load_devices /config 0 1
Total devices: 40
pyinsteon: list_devices
Address   Cat   Subcat Description
'--------  ----- ------ ------------------------------------------------------------------------'
An error occured executing command.
Unknown format code 'x' for object of type 'str'
pyinsteon:

After changing the format string in list_devices (in tools/tools_base.py) to eliminate the ":s", I get
'--------  ----- ------ ------------------------------------------------------------------------'
20.F4.F9  network_bridges  0x15   PowerLinc USB Modem

When invoking find_broken_links, I get an "unsupported format string passed to Address.__format__" error on the first entry.

bash-5.0# python3 run_tool.py
STDOUT: Set log level to 20
The command line module for pyinsteon is designed to test devices and perform certain common functions.
pyinsteon: connect /dev/ttyUSB0
pyinsteon: load_devices /config 0 1
Total devices: 40
pyinsteon: manage_aldb
pyinsteon - aldb: advanced
pyinsteon - advanced: find_broken_links
Device   Mem Addr Target    Group Mode Status
'-------- -------- --------- ----- ---- ----------------------------------------'
An error occured executing command.
unsupported format string passed to Address.__format__

After hacking/debugging, it seems the addresses can't be formatted as strings(?).

After changing the format string in tools/advanced.py to eliminate the :s format on the source and target addresses, I get:

'-------- -------- --------- ----- ---- ----------------------------------------'
20.F4.F9     1fff 14.8E.0F     1   C Missing responder

Not sure if there is some deeper issue...

**Comment by teharris1** [comment]
This was resolved in 1.0.11
