### ISSUE TITLE
Question: Example of how to link a device without the set buttons?

### ISSUE THREAD

**Issue by billchurch** [pyinsteon/pyinsteon#66]
I'm looking at switching over to the native Insteon component in Home Assistant, and at the same time I want to move from an Insteon Hub (unreliable) to an Insteon PLM (USB).

I have the insteon_tools loaded on a machine with the PLM and I'm testing with a couple of devices I don't use actively, but I'm not having success adding / linking a device to the PLM without physically pairing. 

My main use case here is I have a few of these modules buried in the ceiling and I'm trying to avoid getting a ladder and taking stuff apart. 

You can do this with the native Insteon App with the Hub, so I was hoping there was a formula to do it with the `insteon_tools`.

**Comment by john-beck** [comment]
I would be interested in this as well.

I was wondering if it would be possible to implement a means to move the device links from one PLM to another in the case of a PLM failure or as a backup prior to a failure. 

I was going to look into what pyinsteon could do to achieve this from a 2413S to a 2448A7.

I have only got started looking into whether or not it is possible and ran across billchurch's comment so I thought I would add my interest.

**Comment by teharris1** [comment]
The current command line tool in this branch: 
https://github.com/teharris1/pyinsteon/tree/patch12 

includes the ability to link a device without the set button. It requires you to install as follows:

`python3 -m pip install --upgrade git+https://github.com/teharris1/pyinsteon.git@patch12`

From there run `insteon_tools` connecting to your PLM and link your devices as follows:
```
connect <connection info>
link_device <device address>
```
Run the `link_device` command for each of the devices you want to add. This will link group 0 with the modem as the controller and the device as the responder, which then gives your modem the ability to control the device as needed. To add the full set of recommended links to the device do the following:

```
manage_aldb
add_default_links <device address>
```
Run the `add_default_links` command for each device too.

Keep in mind, not all devices respond to a remote linking request. This only works for newer IC2 devices.

**Comment by teharris1** [comment]
FYI, this patch will be in `pypi` in a month or so. The next patch will be a bug fix patch to address as many of these issues and requests as possible.

**Comment by teharris1** [comment]
@john-beck the ability to add all the links from one modem to another is partially available in this library. However, this requires you to also link all of the devices and update all the devices databases as well. 

What you need to do is:
1. Run `insteon_tools` and connect to your modem.
2. Load the devices (if you need help with this do `help load_devices` at the command prompt). Make sure you load all the ALDBs for all the devices too.
3. In `insteon_tools` go to the `manage_aldb` -> `advanced` menu.
4. Use the `export_aldb` command to export a copy of the device (or modem) aldb to a `json` file (type `help export_aldb` to see the options.
5. Edit the file created with the `export_aldb` command as needed to adjust the ALDB.
6. Use the `replace_aldb` to read the ALDB file to update the ALDB with the edited ALDB recordss.

Keep in mind, steps 4 and 6 requires that the current modem is linked to the device as a controller of group 0. So to replace a modem you would need to link the modem and the device then perform steps 4 - 6. Hope that helps.
