### ISSUE TITLE
insteon_tools -> add_device_to_scene doesn't like decimal input for Ramp Rate

### ISSUE THREAD

**Issue by zimmer62** [pyinsteon/pyinsteon#76]
Running insteon_tools:
aldb
add_device_to_scene

Enter in device address, scene number, on level....

Then it prompts "Ramp rate (Default 0.5):   
If you put in any number or decimal, you get a response: "Must be a number. (Max: 400  Min: 0.1).

If I use the default by hitting enter, I get further errors:
"An error occured executing command.
unsupported operand type(s) for +=: 'int' and 'NoneType'

![image](https://user-images.githubusercontent.com/3384127/110385904-8d73eb00-802d-11eb-95cd-320928b0dbcc.png)

**Comment by teharris1** [comment]
This was fixed in 1.0.11
